### ISSUE TITLE
Investigate failing graalvm-presubmit-shared-config-a (cloud-devrel-kokoro-resources) tests

### ISSUE THREAD

**Issue by alicejli** [googleapis/java-shared-config#752]
PRs are failing in java-shared-config due to failing tests:

graalvm-presubmit-shared-config-a (cloud-devrel-kokoro-resources)
graalvm-presubmit-shared-config-b (cloud-devrel-kokoro-resources) 

They are failing for the same reason:

```
Step #2: Finished generating '/workspace/sdk-platform-java/showcase/gapic-showcase/target/native-tests' in 10m 20s.
Step #2: [INFO] Executing: /workspace/sdk-platform-java/showcase/gapic-showcase/target/native-tests --xml-output-dir /workspace/sdk-platform-java/showcase/gapic-showcase/target/native-test-reports -Djunit.platform.listeners.uid.tracking.output.dir=/workspace/sdk-platform-java/showcase/gapic-showcase/target/test-ids
Step #2: JUnit Platform on Native Image - report
Step #2: ----------------------------------------
Step #2: 
Step #2: Exception in thread "main" java.lang.NoSuchMethodError: org.junit.platform.engine.TestDescriptor.getAncestors()
Step #2: 	at org.junit.platform.launcher.core.StackTracePruningEngineExecutionListener.getTestClassNames(StackTracePruningEngineExecutionListener.java:50)
Step #2: 	at org.junit.platform.launcher.core.StackTracePruningEngineExecutionListener.executionFinished(StackTracePruningEngineExecutionListener.java:39)
Step #2: 	at org.junit.platform.launcher.core.DelegatingEngineExecutionListener.executionFinished(DelegatingEngineExecutionListener.java:46)
Step #2: 	at org.junit.platform.launcher.core.OutcomeDelayingEngineExecutionListener.reportEngineFailure(OutcomeDelayingEngineExecutionListener.java:83)
Step #2: 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:203)
Step #2: 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:169)
Step #2: 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:93)
Step #2: 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:58)
Step #2: 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:141)
Step #2: 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:57)
Step #2: 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:103)
Step #2: 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:94)
Step #2: 	at org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:52)
Step #2: 	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:70)
Step #2: 	at org.graalvm.junit.platform.NativeImageJUnitLauncher.execute(NativeImageJUnitLauncher.java:74)
Step #2: 	at org.graalvm.junit.platform.NativeImageJUnitLauncher.main(NativeImageJUnitLauncher.java:129)
```

It seems like JUnit 5 introduced the method `getAncestors():` (https://junit.org/junit5/docs/5.10.0-RC1/release-notes/). It's likely we need to update the JUnit dependency for gapic-showcase to use JUnit 5 here: https://github.com/googleapis/sdk-platform-java/blob/main/showcase/pom.xml#L60, but I'm not positive.

**Comment by mpeddada1** [comment]
Thanks for investigating @alicejli! Fixed with https://github.com/googleapis/java-shared-config/pull/746
